INSERT INTO realty SET `name` = 'квартиры';
INSERT INTO realty SET `name` = 'дома';
INSERT INTO realty SET `name` = 'коммерческая недвижимость';
INSERT INTO realty SET `name` = 'офисы';
INSERT INTO realty SET `name` = 'участки';
INSERT INTO realty SET `name` = 'гаражи';

INSERT INTO realtyDetail SET `name` = 'квартира', `realty_id` = 1;
INSERT INTO realtyDetail SET `name` = 'комната', `realty_id` = 1;
INSERT INTO realtyDetail SET `name` = 'дом', `realty_id` = 2;
INSERT INTO realtyDetail SET `name` = 'часть дома', `realty_id` = 2;
INSERT INTO realtyDetail SET `name` = 'дача', `realty_id` = 2;
INSERT INTO realtyDetail SET `name` = 'коттедж', `realty_id` = 2;
INSERT INTO realtyDetail SET `name` = 'таунхаус', `realty_id` = 2;
INSERT INTO realtyDetail SET `name` = 'торговые площади', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'складские помещения', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'производственные помещения', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'кафе, бар, ресторан', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'объект сферы услуг', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'отель, гостиница', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'база отдыха, пансионат', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'помещения свободного назначения', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'готовый бизнес', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'зал', `realty_id` = 3;
INSERT INTO realtyDetail SET `name` = 'офисное помещение', `realty_id` = 4;
INSERT INTO realtyDetail SET `name` = 'офисное здание', `realty_id` = 4;
INSERT INTO realtyDetail SET `name` = 'участок под жилую застройку', `realty_id` = 5;
INSERT INTO realtyDetail SET `name` = 'земля коммерческого назначения', `realty_id` = 5;
INSERT INTO realtyDetail SET `name` = 'земля сельскохозяйственного назначения', `realty_id` = 5;
INSERT INTO realtyDetail SET `name` = 'земля рекреационного назначения', `realty_id` = 5;
INSERT INTO realtyDetail SET `name` = 'бокс в гаражном комплексе', `realty_id` = 6;
INSERT INTO realtyDetail SET `name` = 'подземный паркинг', `realty_id` = 6;
INSERT INTO realtyDetail SET `name` = 'место в гаражном кооперативе', `realty_id` = 6;
INSERT INTO realtyDetail SET `name` = 'отдельно стоящий гараж', `realty_id` = 6;
INSERT INTO realtyDetail SET `name` = 'место на стоянке', `realty_id` = 6;

INSERT INTO property SET `name` = 'продажа';
INSERT INTO property SET `name` = 'долгосрочная аренда';
INSERT INTO property SET `name` = 'посуточная аренда';

INSERT INTO material SET `name` = 'кирпич';
INSERT INTO material SET `name` = 'силикатный кирпич';
INSERT INTO material SET `name` = 'панель';
INSERT INTO material SET `name` = 'монолит';
INSERT INTO material SET `name` = 'ракушечник';
INSERT INTO material SET `name` = 'монолитно-кирпичный';
INSERT INTO material SET `name` = 'монолитно-блочный';
INSERT INTO material SET `name` = 'дерево и кирпич';
INSERT INTO material SET `name` = 'инкерманский камень';
INSERT INTO material SET `name` = 'пеноблок';
INSERT INTO material SET `name` = 'сруб';
INSERT INTO material SET `name` = 'брус';
INSERT INTO material SET `name` = 'каркасно-щитовой';
INSERT INTO material SET `name` = 'глинобитный';
INSERT INTO material SET `name` = 'пенобетон';
INSERT INTO material SET `name` = 'шлакобетон';
INSERT INTO material SET `name` = 'газобетон';
INSERT INTO material SET `name` = 'сендвич-панели';
INSERT INTO material SET `name` = 'метал';
INSERT INTO material SET `name` = 'поротерм';

INSERT INTO `object` SET `name` = 'Торгово-развлекательный комплекс';
INSERT INTO `object` SET `name` = 'Торгово-офисный центр';
INSERT INTO `object` SET `name` = 'Нежилое помещение в жилом доме';
INSERT INTO `object` SET `name` = 'Здание / комплекс / павильон';
INSERT INTO `object` SET `name` = 'Киоск';
INSERT INTO `object` SET `name` = 'Торговое место';
INSERT INTO `object` SET `name` = 'Помещение (часть здания)';
INSERT INTO `object` SET `name` = 'Здание / комплекс';
INSERT INTO `object` SET `name` = 'Площадка';
INSERT INTO `object` SET `name` = 'Бизнес центр';
INSERT INTO `object` SET `name` = 'Торгово-офисный центр';
INSERT INTO `object` SET `name` = 'Административное здание';
INSERT INTO `object` SET `name` = 'Особняк';
INSERT INTO `object` SET `name` = 'Нежилое помещение в жилом доме';

INSERT INTO `newbuilding` SET `name` = 'вторичный рынок';
INSERT INTO `newbuilding` SET `name` = 'новострой';

INSERT INTO `sphere` SET `name` = 'торговля';
INSERT INTO `sphere` SET `name` = 'производство продуктов питания';
INSERT INTO `sphere` SET `name` = 'производство непродовольственных товаров';
INSERT INTO `sphere` SET `name` = 'строительство';
INSERT INTO `sphere` SET `name` = 'транспорт / автосервис';
INSERT INTO `sphere` SET `name` = 'информационные технологии';
INSERT INTO `sphere` SET `name` = 'сельское хозяйство';
INSERT INTO `sphere` SET `name` = 'общественное питание';
INSERT INTO `sphere` SET `name` = 'финансово / страховые услуги';
INSERT INTO `sphere` SET `name` = 'образование';
INSERT INTO `sphere` SET `name` = 'бытовые услуги';
INSERT INTO `sphere` SET `name` = 'медицина и фармакология';
INSERT INTO `sphere` SET `name` = 'спортивно-оздоровительные услуги';
INSERT INTO `sphere` SET `name` = 'развлекательные услуги';
INSERT INTO `sphere` SET `name` = 'гостиничные услуги';
INSERT INTO `sphere` SET `name` = 'автосервис';
INSERT INTO `sphere` SET `name` = 'АЗС';
INSERT INTO `sphere` SET `name` = 'СМИ / полиграфия';
INSERT INTO `sphere` SET `name` = 'разработка полезных ископаемых';
INSERT INTO `sphere` SET `name` = 'сдача в аренду';

INSERT INTO `appointment` SET `name` = 'под легковое авто';
INSERT INTO `appointment` SET `name` = 'под бус';
INSERT INTO `appointment` SET `name` = 'под грузовик / автобус';
INSERT INTO `appointment` SET `name` = 'универсальный';
INSERT INTO `appointment` SET `name` = 'под катер / яхту';

INSERT INTO `squareLandUnit` SET `name` = 'сотка';
INSERT INTO `squareLandUnit` SET `name` = 'га';
INSERT INTO `squareLandUnit` SET `name` = 'кв.м.';

INSERT INTO `currency` SET `name` = 'долларов';
INSERT INTO `currency` SET `name` = 'гривен';
INSERT INTO `currency` SET `name` = 'евро';

INSERT INTO `costType` SET `name` = 'за объект';
INSERT INTO `costType` SET `name` = 'за кв.м.';
INSERT INTO `costType` SET `name` = 'за участок';
INSERT INTO `costType` SET `name` = 'за сотку';
INSERT INTO `costType` SET `name` = 'за гектар';

INSERT INTO `exchange` SET `name` = 'нет';
INSERT INTO `exchange` SET `name` = 'на авто + моя доплата';
INSERT INTO `exchange` SET `name` = 'на авто без доплаты';
INSERT INTO `exchange` SET `name` = 'на авто + ваша доплата';
INSERT INTO `exchange` SET `name` = 'на недвижимость + моя доплата';
INSERT INTO `exchange` SET `name` = 'на недвижимость без доплаты';
INSERT INTO `exchange` SET `name` = 'на недвижимость + ваша доплата';
INSERT INTO `exchange` SET `name` = 'рассмотрю любой вариант';

INSERT INTO `typeOffer` SET `name` = 'от посредника';
INSERT INTO `typeOffer` SET `name` = 'от представителя хозяина (без комиссионных)';
INSERT INTO `typeOffer` SET `name` = 'от собственника';

INSERT INTO `fees` SET `name` = 'нет';
INSERT INTO `fees` SET `name` = 'плата по счетчикам';
INSERT INTO `fees` SET `name` = 'плата по счетчикам за отопление';

INSERT INTO `business` SET `name` = 'Нет';
INSERT INTO `business` SET `name` = 'Да';

INSERT INTO `ourParams` SET `var` = 'region_id', `type1` = '1', `type2` = '1', `label` = 'Регион';
INSERT INTO `ourParams` SET `var` = 'district_id', `type1` = '1', `type2` = '1', `label` = 'НП-1';
INSERT INTO `ourParams` SET `var` = 'town_id', `type1` = '1', `type2` = '1', `label` = 'НП-2';
INSERT INTO `ourParams` SET `var` = 'microDistrict_id', `type1` = '1', `type2` = '1', `label` = 'МикроРайон';
INSERT INTO `ourParams` SET `var` = 'street_id', `type1` = '1', `type2` = '1', `label` = 'Улица';
INSERT INTO `ourParams` SET `var` = 'realty_id', `type1` = '1', `type2` = '0', `label` = 'Категория';
INSERT INTO `ourParams` SET `var` = 'realtyDetail_id', `type1` = '1', `type2` = '0', `label` = 'Тип недвижимости';
INSERT INTO `ourParams` SET `var` = 'property_id', `type1` = '1', `type2` = '0', `label` = 'Тип операции';
INSERT INTO `ourParams` SET `var` = 'object_id', `type1` = '1', `type2` = '1', `label` = 'Тип объекта';
INSERT INTO `ourParams` SET `var` = 'newbuilding_id', `type1` = '1', `type2` = '0', `label` = 'Новострой';
INSERT INTO `ourParams` SET `var` = 'material_id', `type1` = '1', `type2` = '0', `label` = 'Тип стен';
INSERT INTO `ourParams` SET `var` = 'sphere_id', `type1` = '1', `type2` = '0', `label` = 'Сфера';
INSERT INTO `ourParams` SET `var` = 'appointment_id', `type1` = '1', `type2` = '1', `label` = 'Назначение';
INSERT INTO `ourParams` SET `var` = 'typeOffer_id', `type1` = '1', `type2` = '1', `label` = 'Тип предложения';
INSERT INTO `ourParams` SET `var` = 'exchange_id', `type1` = '1', `type2` = '1', `label` = 'Обмен';
INSERT INTO `ourParams` SET `var` = 'squareLandUnit_id', `type1` = '1', `type2` = '0', `label` = 'ед. измерения';
INSERT INTO `ourParams` SET `var` = 'currency_id', `type1` = '1', `type2` = '0', `label` = 'Валюта';
INSERT INTO `ourParams` SET `var` = 'costType_id', `type1` = '1', `type2` = '0', `label` = 'Тип цены';
INSERT INTO `ourParams` SET `var` = 'fees_id', `type1` = '1', `type2` = '1', `label` = 'Доп. платежи';
INSERT INTO `ourParams` SET `var` = 'business_id', `type1` = '1', `type2` = '1', `label` = 'Действующий бизнес';
INSERT INTO `ourParams` SET `var` = 'rooms', `type1` = '0', `type2` = '2', `label` = 'Количество комнат';
INSERT INTO `ourParams` SET `var` = 'squareFull', `type1` = '0', `type2` = '2', `label` = 'Площадь общая';
INSERT INTO `ourParams` SET `var` = 'squareLive', `type1` = '0', `type2` = '2', `label` = 'Площадь жилая';
INSERT INTO `ourParams` SET `var` = 'squareKitchen', `type1` = '0', `type2` = '2', `label` = 'Площадь кухня';
INSERT INTO `ourParams` SET `var` = 'costSell', `type1` = '0', `type2` = '2', `label` = 'Цена';
INSERT INTO `ourParams` SET `var` = 'costMonth', `type1` = '0', `type2` = '2', `label` = 'Цена за месяц';
INSERT INTO `ourParams` SET `var` = 'costDay', `type1` = '0', `type2` = '2', `label` = 'Цена за сутки';
INSERT INTO `ourParams` SET `var` = 'costWeek', `type1` = '0', `type2` = '2', `label` = 'Цена за неделю';
INSERT INTO `ourParams` SET `var` = 'costHour', `type1` = '0', `type2` = '2', `label` = 'Цена за час';
INSERT INTO `ourParams` SET `var` = 'bedroomsCount', `type1` = '0', `type2` = '2', `label` = 'Количество спален';
INSERT INTO `ourParams` SET `var` = 'roomsCount', `type1` = '0', `type2` = '2', `label` = 'Количество помещений';
INSERT INTO `ourParams` SET `var` = 'sleeps', `type1` = '0', `type2` = '2', `label` = 'Спальных мест';
INSERT INTO `ourParams` SET `var` = 'seatsHall', `type1` = '0', `type2` = '2', `label` = 'Количество мест';
INSERT INTO `ourParams` SET `var` = 'squareLand', `type1` = '0', `type2` = '2', `label` = 'Площадь земли/участка общая';
INSERT INTO `ourParams` SET `var` = 'squareUseful', `type1` = '0', `type2` = '2', `label` = 'Площадь полезная';
INSERT INTO `ourParams` SET `var` = 'parkingCount', `type1` = '0', `type2` = '2', `label` = 'Машиномест';
INSERT INTO `ourParams` SET `var` = 'floor', `type1` = '0', `type2` = '1', `label` = 'Этаж', `min_value` = 1, `max_value` = 46;
INSERT INTO `ourParams` SET `var` = 'numberOfFloors', `type1` = '0', `type2` = '1', `label` = 'Этажность', `min_value` = 1, `max_value` = 46;
INSERT INTO `ourParams` SET `var` = 'numberOfFloorsResidential', `type1` = '0', `type2` = '1', `label` = 'Жилых этажей', `min_value` = 1, `max_value` = 46;
INSERT INTO `ourParams` SET `var` = 'house_number', `type1` = '0', `type2` = '2', `label` = 'Номер дома';
INSERT INTO `ourParams` SET `var` = 'description', `type1` = '0', `type2` = '3', `label` = 'Описание';